### ISSUE TITLE
Could not find certificate with thumbprint

### ISSUE THREAD

**Issue by Ar2rZ** [digipost/digipost-api-client-dotnet#100]
Hi, Dev from Eschergroup here.

We still have an issue with certificate. Digipost API version used - 7.2.0

All steps where made as per instructions -  http://digipost.github.io/digipost-api-client-dotnet/v7.0/ 
User access rights are same as per certificate installation. Visual Studio is is running as administrator.

After running test, exception is thrown on line - `var client = new DigipostClient(config, "‎.....");`

System.Management.Instrumentation.InstanceNotFoundException was unhandled
  HResult=-2146233088
  Message=Could not find certificate with thumbprint: [.......]
  Source=ApiClientShared
  StackTrace:
       at ApiClientShared.CertificateUtility.GetFirstCertificateOrThrowException(String thumbprint, StoreName storeName, Language errorMessageLanguage)
       at Digipost.Api.Client.DigipostClient..ctor(ClientConfig clientConfig, String thumbprint)
       at Test_003.Program.Main(String[] args) in C:\dev\src\Agents\Test_003\Program.cs:line 26
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by asjafjell** [comment]
Hi, and thank you for submitting an issue. I would like to know more about your environment. Are you running your application via Visual Studio? If yes, then installing the cert on current user, the one logged in, is good enough. If deploying the app and running as for examle administrator, please install on local machine or log in as admin and install certificate. When this is sorted out, do you find the certificate in MMC as expected? Please remember to check "Mark certificate as exportable" during installation. Looking forward to hearing from you.




On Tue, Feb 21, 2017 at 3:41 PM +0100, "Ar2rZ" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, Dev from Eschergroup here.

We still have an issue with certificate. Digipost API version used - 7.2.0

All steps where made as per instructions - http://digipost.github.io/digipost-api-client-dotnet/v7.0/
User access rights are same as per certificate installation. Visual Studio is is running as administrator.

After running test, exception is thrown on line - var client = new DigipostClient(config, "‎.....");

System.Management.Instrumentation.InstanceNotFoundException was unhandled
HResult=-2146233088
Message=Could not find certificate with thumbprint: [.......]
Source=ApiClientShared
StackTrace:
at ApiClientShared.CertificateUtility.GetFirstCertificateOrThrowException(String thumbprint, StoreName storeName, Language errorMessageLanguage)
at Digipost.Api.Client.DigipostClient..ctor(ClientConfig clientConfig, String thumbprint)
at Test_003.Program.Main(String[] args) in C:\dev\src\Agents\Test_003\Program.cs:line 26
at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
InnerException:

**Comment by asjafjell** [comment]
I heard from Nicolay that you were able to solve the issue. May I ask what the problem was?

**Comment by Ar2rZ** [comment]
Hi, sorted for now, 
Was looking for certificate thumbprint in incorrect place. so, by using incorrect thumbprint cause this issue. it works now.
Thanks.

**Comment by asjafjell** [comment]
No problem!
