### ISSUE TITLE
UnexpectedResponseException: ErrorType:SERVER

### ISSUE THREAD

**Issue by andreasle** [digipost/digipost-api-client-dotnet#175]
Hei,
Vi får en UnexpectedResponseException ved kall til `await portalClient.GetStatusChange();` i produksjonsmiljø hos kunde med orgnummer 921627009. Tenker at det usannsynlig at det er en `TooEagerPollingException `siden det går et kall hver andre time? Kan dere se årsaken til feilen?

Stacktrace:
> Digipost.Signature.Api.Client.Core.Exceptions.UnexpectedResponseException: ErrorType:SERVER, ErrorCode: GENERAL_ERROR, ErrorMessage: 
>    at Digipost.Signature.Api.Client.Portal.PortalClient.<GetStatusChange>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at eDocument.Integration.DifiSignering.SignPoller.<GetStatuses>d__4.MoveNext() in C:\code\edocument\eDocument.Integration\DifiSignering\SignPoller.cs:line 69

**Comment by johnksv** [comment]
Hei. Dette issuet skulle vært åpnet i repoet for api-klienten til signeringstjenesten ( https://github.com/digipost/signature-api-client-dotnet ). Jeg overfører issuet dit.
